version: '3.4'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  app1:
      build: .
      ports:
        - "8080"
      environment:
        DB_URL: "mongodb://mongo:27017"
        REDIS_URL: "redis://redis"
      depends_on:
        - mongo
        - redis
  app2:
      build: .
      ports:
        - "8080"
      environment:
        DB_URL: "mongodb://mongo:27017"
        REDIS_URL: "redis://redis"
      depends_on:
        - mongo
        - redis
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'